# Building a Reference Dataframe for Dog individual Information

I will build a reference table which contains personal information on each greyhound.

This is something that eventually be done in SQL as this is much faster.  This notebook is more a demonstration of initial thoughts of the overall structure and will lead to the implentation later on of my overall schema for how the realtional databases speak to each other.

This will include things like:

- Sex
- Trainer
- Birth date

This can then be used for updating both the main table and the table that stores each greyhounds personal race information:

![body](./images/reference_relationship.png)

In [1]:
import pandas as pd
import numpy as np
from datetime import datetime

from sqlalchemy import create_engine
engine = create_engine('postgresql://localhost:5432/danielpayne')

In [2]:
crayford = pd.read_sql("SELECT * FROM crayford_updated_imputed;", engine)

In [3]:
# First the Name Dictionary that contains the race history

crayford_name_dict = {}
for name in crayford.name.unique():
    df = crayford.loc[crayford.name == name]
    crayford_name_dict[name] = df

In [4]:
# Initialise Dataframe by taking every indivdual greyhound name
crayford_greyhound_info = pd.DataFrame({'Name': crayford.name.unique()})
crayford_greyhound_info

                  Name
0       Have Anice Day
1       Blackrose Jake
2      Gringos Maestro
3        Farloe Cassie
4            Code Ella
5        Seagrave Bolt
6        Dims Champion
7     Florentine Flame
8      Hollyhill Tiger
9           Upagumtree
10        Kilvane Hawk
11     Ultimate Bundle
12        Lemming Vane
13      Trapstyle Blue
14          Tinas Fred
15        Try Plan Bee
16      Trumpers Gemma
17      Tommys Diamond
18     Hollyoak Nikita
19         Cronody Pat
20      Mulroy Hustler
21        Abbeys Sandy
22       Chuckles Girl
23         Baby Danger
24     Supersonic Star
25         Group Vespa
26        Calm Down Da
27         Pullyasoxup
28    Nancyfromnairobi
29       Wessie Beauty
...                ...
1339     Moyeedy Alice
1340           Subzero
1341     Sporting Hero
1342        Lennys Boy
1343         Mallowney
1344       Racy Master
1345      Zenas Smiley
1346          Euphemus
1347    Freedom Reagan
1348  Steeple Rd Betsy
1349   Sporting Cabana
1350    Whistling Mall
1351      Skiproe Rose
1352  Rocky The Legend
1353   Whats Lily Upto
1354       Lulus Poppy
1355       Newlawn Ned
1356     Reagrove Aero
1357        Falsom Act
1358        Scala Mink
1359     Ashford Rosie
1360    Newlawn Marian
1361     Pretend Times
1362      Droopys Hyde
1363     Corrough Brae
1364  Goodtogohoneygar
1365     Sapphire Rose
1366      Bestreaction
1367      Pure Placere
1368       Pure Prince

[1369 rows x 1 columns]

In [18]:
# Now I will reference the dictionary to get some information that is unique to each greyhound:

def sex_finder(name):
    sex = crayford_name_dict[name].iloc[0]['male']
    return sex

def trainer_finder(name):
    trainer = crayford_name_dict[name].iloc[0]['trainer']
    return trainer
    
def born_finder(name):
    born = crayford_name_dict[name].iloc[0]['born']
    return born

In [ ]:
# Create male column 
crayford_greyhound_info['male'] = crayford_greyhound_info.Name.map(lambda x: sex_finder(x))

In [16]:
# Create trainer column and check for any duplicate/mis-spelled values
crayford_greyhound_info['trainer'] = crayford_greyhound_info.Name.map(lambda x: trainer_finder(x))
crayford_greyhound_info.trainer.value_counts()

B D O'sullivan     186
K M O'Flaherty     142
J J Luckhurst      126
A C B Green        109
G L Davidson        98
M N Fenwick         96
D Childs            94
I P Stevens         80
J M Liles           78
P A Tompsett        71
J Daly              67
T M Levers          61
S J Gammon          49
N F Carter          15
M A Wallis          11
H P J Kemp           8
P W Young            8
R J Holloway         8
M H Fawsitt          4
J G Mullins          4
K P Boon             4
A M Kibble           3
R C Boosey           3
J J March            3
E A Gaskin           3
A J Taylor           2
J E Harvey           2
P J Dolby            2
K R Hutton           2
P Wood               2
H J Dimmock          2
K J Cobbold          2
A Kelly-Pilgrim      2
Unknown              2
J T Foster           2
P A Sallis           1
P J Simmonds         1
J Bloomfield         1
A B Gifkins          1
M J Dartnall         1
N Mcellistrim        1
D Ruth               1
R H Joyce            1
D D Knight           1
D P Brabon           1
P Hennessy           1
P R Garland          1
A M P Collett        1
D Power              1
R Devenish           1
P J Dale             1
M T Newman           1
J Campbell           1
Name: Name, dtype: int64

In [12]:
# Change the Trainers so they are all the same format
crayford_greyhound_info.trainer = crayford_greyhound_info.trainer.map(lambda x: "K M O'Flaherty" if x == "Katie O'Flaherty" else x)
crayford_greyhound_info.trainer = crayford_greyhound_info.trainer.map(lambda x: "B D O'sullivan" if x == "Barry O'Sullivan" else x)
crayford_greyhound_info.trainer = crayford_greyhound_info.trainer.map(lambda x: "A C B Green" if x == "Arun Green" else x)
crayford_greyhound_info.trainer = crayford_greyhound_info.trainer.map(lambda x: "M N Fenwick" if x == "Mark Fenwick" else x)
crayford_greyhound_info.trainer = crayford_greyhound_info.trainer.map(lambda x: "J J Luckhurst" if x == "Julie Luckhurst" else x)
crayford_greyhound_info.trainer = crayford_greyhound_info.trainer.map(lambda x: "I P Stevens" if x == "Ian Stevens" else x)
crayford_greyhound_info.trainer = crayford_greyhound_info.trainer.map(lambda x: "T M Levers" if x == "Tom Levers" else x)
crayford_greyhound_info.trainer = crayford_greyhound_info.trainer.map(lambda x: "J Daly" if x == "Jim Daly" else x)
crayford_greyhound_info.trainer = crayford_greyhound_info.trainer.map(lambda x: "G L Davidson" if x == "Gemma Davidson" else x)
crayford_greyhound_info.trainer = crayford_greyhound_info.trainer.map(lambda x: "D Childs" if x == "Dean Childs" else x)

In [13]:
# Check to see that all names start with an initial!
crayford_greyhound_info.trainer.value_counts()

B D O'sullivan     186
K M O'Flaherty     142
J J Luckhurst      126
A C B Green        109
G L Davidson        98
M N Fenwick         96
D Childs            94
I P Stevens         80
J M Liles           78
P A Tompsett        71
J Daly              67
T M Levers          61
S J Gammon          49
N F Carter          15
M A Wallis          11
H P J Kemp           8
P W Young            8
R J Holloway         8
M H Fawsitt          4
J G Mullins          4
K P Boon             4
A M Kibble           3
R C Boosey           3
J J March            3
E A Gaskin           3
A J Taylor           2
J E Harvey           2
P J Dolby            2
K R Hutton           2
P Wood               2
H J Dimmock          2
K J Cobbold          2
A Kelly-Pilgrim      2
Unknown              2
J T Foster           2
P A Sallis           1
P J Simmonds         1
J Bloomfield         1
A B Gifkins          1
M J Dartnall         1
N Mcellistrim        1
D Ruth               1
R H Joyce            1
D D Knight           1
D P Brabon           1
P Hennessy           1
P R Garland          1
A M P Collett        1
D Power              1
R Devenish           1
P J Dale             1
M T Newman           1
J Campbell           1
Name: Name, dtype: int64

In [19]:
# Create born column 
crayford_greyhound_info['born'] = crayford_greyhound_info.Name.map(lambda x: born_finder(x))

In [34]:
crayford_greyhound_info.columns = [c.lower() for c in crayford_greyhound_info.columns]

In [39]:
crayford_greyhound_info.to_sql('crayford_greyhound_info', engine)

# Possible methods for incorporating into the main dataframe

There would be two main methods for importing this information into the main dataframe or the personal race information dataframe.

- Merge the information in.  Much like an SQL join method
- Map the information in by looking up the value.  Would use this possibly if I continued using pandas/python to update my dataframes

## Merge method example

In [43]:
dummy_test = pd.DataFrame({'name': crayford.name})
dummy_test

                   name
0        Have Anice Day
1        Blackrose Jake
2       Gringos Maestro
3         Farloe Cassie
4             Code Ella
5         Seagrave Bolt
6         Dims Champion
7      Florentine Flame
8       Hollyhill Tiger
9            Upagumtree
10         Kilvane Hawk
11      Ultimate Bundle
12         Lemming Vane
13       Trapstyle Blue
14           Tinas Fred
15         Try Plan Bee
16       Trumpers Gemma
17       Tommys Diamond
18      Hollyoak Nikita
19          Cronody Pat
20       Mulroy Hustler
21         Abbeys Sandy
22        Chuckles Girl
23          Baby Danger
24      Supersonic Star
25          Group Vespa
26         Calm Down Da
27          Pullyasoxup
28     Nancyfromnairobi
29        Wessie Beauty
...                 ...
14606   Greenlane Eddie
14607  Hollyhillcronody
14608      Mikey Junior
14609    Pesky Squirrel
14610     Crinkill Ruby
14611     Ballymac Silk
14612  Ferryforth Style
14613      Lift The Lid
14614     Lets Go Again
14615    Scruffs Tylier
14616    Funny Pleasure
14617     Newlawn Conor
14618    Wolseleys Jazz
14619      Anfield Mary
14620       Batman Flys
14621       Souley Blue
14622     Roberta Irene
14623    Jimmys Greaves
14624       Pure Prince
14625  Fitzlerseemytail
14626    Bellmore Lodge
14627   Stepit Up Louie
14628    Swift Breasley
14629     Razmataz Dazl
14630    Lizzies Horror
14631       Call Him On
14632       Deputy Hawk
14633  Tullymurry Beech
14634     Cronody Susie
14635    Another Adored

[14636 rows x 1 columns]

In [47]:
dummy_test.merge(crayford_greyhound_info, how='left')

                   name  male         trainer       born
0        Have Anice Day   1.0     A C B Green 2012-04-01
1        Blackrose Jake   1.0      S J Gammon 2014-06-01
2       Gringos Maestro   1.0     M N Fenwick 2013-07-01
3         Farloe Cassie   0.0  B D O'sullivan 2011-09-01
4             Code Ella   0.0       J M Liles 2013-06-01
5         Seagrave Bolt   1.0    P A Tompsett 2012-07-01
6         Dims Champion   1.0     I P Stevens 2013-09-01
7      Florentine Flame   0.0    P A Tompsett 2012-01-01
8       Hollyhill Tiger   1.0   J J Luckhurst 2012-05-01
9            Upagumtree   1.0    G L Davidson 2012-08-01
10         Kilvane Hawk   1.0     I P Stevens 2013-05-01
11      Ultimate Bundle   1.0       J M Liles 2012-05-01
12         Lemming Vane   1.0        D Childs 2013-09-01
13       Trapstyle Blue   0.0       J M Liles 2014-05-01
14           Tinas Fred   1.0     A C B Green 2014-02-01
15         Try Plan Bee   1.0     M N Fenwick 2012-04-01
16       Trumpers Gemma   0.0     I P Stevens 2012-10-01
17       Tommys Diamond   1.0   J J Luckhurst 2013-12-01
18      Hollyoak Nikita   0.0      S J Gammon 2012-06-01
19          Cronody Pat   1.0   J J Luckhurst 2011-11-01
20       Mulroy Hustler   0.0       J M Liles 2013-06-01
21         Abbeys Sandy   0.0     A C B Green 2013-03-01
22        Chuckles Girl   0.0    P A Tompsett 2013-03-01
23          Baby Danger   0.0     M N Fenwick 2014-04-01
24      Supersonic Star   1.0  B D O'sullivan 2014-01-01
25          Group Vespa   0.0  B D O'sullivan 2012-11-01
26         Calm Down Da   1.0       J M Liles 2013-06-01
27          Pullyasoxup   1.0  K M O'Flaherty 2013-08-01
28     Nancyfromnairobi   0.0    P A Tompsett 2013-04-01
29        Wessie Beauty   0.0   J J Luckhurst 2012-04-01
...                 ...   ...             ...        ...
14606   Greenlane Eddie   1.0   J J Luckhurst 2015-06-01
14607  Hollyhillcronody   0.0     I P Stevens 2013-04-01
14608      Mikey Junior   1.0     I P Stevens 2013-04-01
14609    Pesky Squirrel   0.0      T M Levers 2014-03-01
14610     Crinkill Ruby   0.0     A C B Green 2014-05-01
14611     Ballymac Silk   0.0    G L Davidson 2014-08-01
14612  Ferryforth Style   0.0  K M O'Flaherty 2014-01-01
14613      Lift The Lid   1.0  K M O'Flaherty 2015-06-01
14614     Lets Go Again   1.0     A C B Green 2013-10-01
14615    Scruffs Tylier   0.0      T M Levers 2014-07-01
14616    Funny Pleasure   0.0     M N Fenwick 2013-12-01
14617     Newlawn Conor   1.0     M N Fenwick 2014-08-01
14618    Wolseleys Jazz   0.0     A C B Green 2014-01-01
14619      Anfield Mary   0.0     M N Fenwick 2014-10-01
14620       Batman Flys   1.0        D Childs 2015-09-01
14621       Souley Blue   0.0        D Childs 2015-09-01
14622     Roberta Irene   0.0     A C B Green 2015-09-01
14623    Jimmys Greaves   1.0  K M O'Flaherty 2015-09-01
14624       Pure Prince   1.0      Arun Green        NaT
14625  Fitzlerseemytail   0.0     I P Stevens 2015-01-01
14626    Bellmore Lodge   1.0          J Daly 2014-10-01
14627   Stepit Up Louie   1.0   J J Luckhurst 2013-02-01
14628    Swift Breasley   1.0      S J Gammon 2013-07-01
14629     Razmataz Dazl   1.0          J Daly 2014-10-01
14630    Lizzies Horror   0.0  K M O'Flaherty 2015-02-01
14631       Call Him On   1.0   J J Luckhurst 2015-06-01
14632       Deputy Hawk   1.0     I P Stevens 2014-05-01
14633  Tullymurry Beech   0.0  B D O'sullivan 2014-03-01
14634     Cronody Susie   0.0     I P Stevens 2014-07-01
14635    Another Adored   0.0      T M Levers 2013-10-01

[14636 rows x 4 columns]

## Mapping Method

In [ ]:
def sex_mapper(name):
    sex = crayford_greyhound_info.loc[crayford_greyhound_info.name == name, 'male']
    return sex